### ISSUE TITLE
Getting error running npx create-keystone-app app-name

### ISSUE THREAD

**Issue by Sheryar10** [bradtraversy/keystone-blog#1]
Hi, I know this error is not associated with the code you provided. I am having this error when I run the command
### npx create-keystone-app app-name
I have searched almost everything on google and nothing helped me. I also get this error whenever I am installing something with npm

### Error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @apollo/client@3.3.11
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.3.10" from @keystonejs/fields@22.0.0
npm ERR!     node_modules/@keystonejs/fields
npm ERR!       @keystonejs/fields@"^22.0.0" from @keystonejs/fields-auto-increment@8.1.4
npm ERR!       node_modules/@keystonejs/fields-auto-increment
npm ERR!         @keystonejs/fields-auto-increment@"^8.1.4" from @keystonejs/adapter-knex@13.0.1
npm ERR!         node_modules/@keystonejs/adapter-knex
npm ERR!         1 more (@keystonejs/adapter-prisma)
npm ERR!       1 more (@keystonejs/fields-mongoid)
npm ERR!   peer react@"^16.13.1" from @arch-ui/alert@0.0.18
npm ERR!   node_modules/@arch-ui/alert
npm ERR!     @arch-ui/alert@"^0.0.18" from @keystonejs/fields@22.0.0
npm ERR!     node_modules/@keystonejs/fields
npm ERR!       @keystonejs/fields@"^22.0.0" from @keystonejs/fields-auto-increment@8.1.4
npm ERR!       node_modules/@keystonejs/fields-auto-increment
npm ERR!         @keystonejs/fields-auto-increment@"^8.1.4" from @keystonejs/adapter-knex@13.0.1
npm ERR!         node_modules/@keystonejs/adapter-knex
npm ERR!         1 more (@keystonejs/adapter-prisma)
npm ERR!       1 more (@keystonejs/fields-mongoid)
npm ERR!   48 more (@arch-ui/button, @arch-ui/controls, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-dom@17.0.1
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^17.0.1" from @keystonejs/fields@22.0.0
npm ERR!   node_modules/@keystonejs/fields
npm ERR!     @keystonejs/fields@"^22.0.0" from @keystonejs/fields-auto-increment@8.1.4
npm ERR!     node_modules/@keystonejs/fields-auto-increment
npm ERR!       @keystonejs/fields-auto-increment@"^8.1.4" from @keystonejs/adapter-knex@13.0.1
npm ERR!       node_modules/@keystonejs/adapter-knex
npm ERR!       1 more (@keystonejs/adapter-prisma)
npm ERR!     1 more (@keystonejs/fields-mongoid)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\HP\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2021-02-16T06_08_39_890Z-debug.log

Please help me with this. I am so stuck right now.

Thanks

**Comment by ghost** [comment]
I am having the same issue with npm version 7.x.x. Did some research online but couldn't find related issue and solution. Problem resolved when I tried again with npm 6.14.11.

**Comment by Sheryar10** [comment]
Thanks for the reply. How do I downgrade it?

**Comment by Sheryar10** [comment]
And also which version would do the trick?

**Comment by ghost** [comment]
To use difference version of node/downgrade it, it's depends how you initially install the node in your machine.

For me, node 12.20.2, and npm 6.14.11 will do the trick.

**Comment by Sheryar10** [comment]
Ok, thanks for the help
